@startuml 

abstract class Payment {
    -amount()
    -paymentDate()
    -transactionld()
    +getamount : amount()
    +getpaymentDate : paymentDate ()
    +gettransactionld : transactionld ()
    }
interface processPayment

class CashPayment  {
    -cashProvided()
    +getcashProvided : cashProvided()
}
Payment--|>CashPayment
class CardPayment {
    -numbercard()
    -namesuser()
    -DateEnd()
    +getnumbercard() : numbercard ()
    +getnamesuser() : namesuser ()
    +getDateEnd() : DateEnd ()

    }
interface processvalidation
Payment--|>CardPayment
CardPayment..|>processPayment
CashPayment..|>processPayment
CashPayment..|>processvalidation
Class PaymentManager{
    processALLPayments()
}
Payment--|>PaymentManager
PaymentManager..|>processPayment


@enduml