@startuml Diagramm

abstract class Payment {
  - amount: double
  - paymentDate: Date
  - transactionId: String
  + getAmount(): double
  + getPaymentDate(): Date
  + getTransactionId(): String
}

class CashPayment {
  - cashProvided: double
  + getCashProvided(): double
  + processPayment()
  + validate()
}

class CardPayment {
  - numberCard: String
  - nameUser: String
  - dateEnd: Date
  + getNumberCard(): String
  + getNameUser(): String
  + getDateEnd(): Date
  + processPayment()
  + validate()
}

class PaymentManager {
  - payments: List<Payment>
  + addPayment(payment: Payment)
  + processAllPayments()
}

interface IProcessPayment {
  + processPayment()
}

interface IProcessValidation {
  + validate()
}

CashPayment ..|> IProcessPayment : implements
CashPayment ..|> IProcessValidation : implements
CardPayment ..|> IProcessPayment : implements

Payment <|-- CashPayment
Payment <|-- CardPayment
PaymentManager o--> "many" Payment : contains

@enduml