@startuml
actor Customer as U
participant "WEB UI" as UI
participant "Order controller" as C
participant "Payment Service" as PS
database "база данных" as DB 

U -> UI :запрос на оформление заказа
UI -> C :передача данных заказа
C -> DB :сохранение заказа
C -> PS :проведение платежа
PS -> C :результат платежа
C -> UI :подтверждение платежа
UI -> U :информирование покупателя