@startuml And_Xor
    start
    :Регистрация/Вход в аккаунт;
    fork
      :Клиент зарегистрирован;
    fork again
      :Клиенту необходима регистрация;
      end fork
      :Подтверждение учетных данных клиента;
      :Выбор товара и добавление в корзину;
      :Выбор способа доставки и оплаты;
      if(товар в наличии?) then (да)
       :оформление заказа;
       else(нет)
       :Уведомление клиента о недоступности товара;
       :Выбор другого товара или удаление отсутствующего из заказа;
      endif
      

      
    stop
@enduml