@startuml And_Xor
    start
    :Регистрация/Вход в аккаунт;
    fork
      :Клиент зарегистрирован;
    fork again
      :Клиенту необходима регистрация;
    end fork
      :Подтверждение учетных данных клиента;
      :Выбор товара и добавление в корзину;
      :Выбор способа доставки и оплаты; 
      if(товар в наличии?) then (Да)
             :Оформление заказа;
       else (нет)
       :Уведомление клиента о недоступности товара;
       :Выбор другого товара или удаление отсутствующего из заказа;
       endif
        fork
         if(Оплата прошла успешно?) then(да)
         :Генерация счет-фактуры;
         :Уведомление клиента о подтверждении заказа и статусе доставки;
         :Заказ отправлен; 
         else (нет)
         :Уведомление клиента о проблеме с платежом;
          if (Просьба клиента повторить попытку или сменить способ оплаты) then (да)
           :Повторная попытка оплаты;
           else(нет)
           :Заказ отменен. Возврат средств Клиенту;
           endif
          endif 
        fork again
        :Проведение транзакции;
        fork again
        :Уведомление склада о необходимости собрать заказ;
        fork again
        :Комплектация заказа;
        end fork   
        :Обновление статуса заказа в системе;
        :Уведомление клиента о каждом изменении статуса заказа;
        stop
 

@enduml