@startuml And_Xor
    start
    :Регистрация/Вход в аккаунт;
    fork
      :Клиент зарегистрирован;
    fork again
      :Клиенту необходима регистрация;
      end fork
      :Подтверждение учетных данных клиента;
      :Выбор товара и добавление в корзину;
      :Выбор способа доставки и оплаты; 
      if(товар в наличии?) then (нет)
       :Уведомление клиента о недоступности товара;
       :Выбор другого товара или удаление отсутствующего из заказа;
       stop
       else(да)
       :Оформление заказа;
        fork
        :Оплата заказа;
        fork again
        :Проверка платежных деталей и проведение транзации; 
        fork again
        :Уведомление склада о необходимости сборки заказа;
        fork again
        :комплектация заказа по списку;
        end fork
    if(оплата прошла?) then (нет)
      :Уведомление клиента о проблеме с платежом;
      :предложение клиенту изменить способ оплаты.отмена заказа в случае несогласия;
      stop
    else(да)
      :генерация счет-фактуры;
      :уведомление клиента о подтверждении заказа;
      :заказ отправлен;
      :Обновление статуса заказа по мере его продвижения к доставке;
      :Отправка уведомления клиенту о каждом изменении статуса заказа;
    stop
@enduml